#!/bin/bash
#Program to convert digits to whole word using case / esac 
# from the prompt e.g.  ./enter0-9 9 
# returns e.g.  9 
#               nine
varname=$1
echo $varname
case $varname in
	0) echo zero
	;;
	1) echo one
	;;
	2) echo two
	;;
	3) echo three
	;;
	4) echo four
	;;
	5) echo five
	;;
	6) echo six
	;;
	7) echo seven
	;;
	8) echo eight
	;;
	9) echo nine
	;;
esac
